name: "Sphinx Documentation"

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Get branch name
      id: branch-name
      uses: tj-actions/branch-names@v5
    - name: Build Sphinx Docker
      env:
        BRANCH: ${{ steps.branch-name.outputs.current_branch }}
      working-directory: ./sphinx
      run: |
        docker build . -t deephaven-ib/sphinx --build-arg VERSION=latest --build-arg DH_IB_VERSION=${BRANCH} --build-arg DH_IB_BRANCH=${BRANCH}
    - name: Run Sphinx Docker
      working-directory: ./sphinx
      run: |
        echo "DEBUG: IMAGES"
        docker images
        echo "DEBUG: RUN"
        docker run -v `pwd`/build/:/build/deephaven-ib/sphinx/build/ deephaven-ib/sphinx
        echo "DEBUG: FIND"
        find ./build
        echo "DEBUG: DONE"
    - uses: actions/upload-artifact@v1
      with:
        name: DocumentationHTML
        path: sphinx/build/html/
    - name: Deploy to gh-pages
      uses: JamesIves/github-pages-deploy-action@v4.2.3
      if: github.event.pull_request.merged == true
        with:
          branch: gh-pages
          folder: sphinx/build/html/
